### ISSUE TITLE
Worksheet.GetLastRowNumber method returns false row count

### ISSUE THREAD

**Issue by rgallini** [rabanti-github/NanoXLSX#16]
Using a simple table with 7 rows and 13 columns, GetLastRowNumber returns 11. Sample file is attached.
[testdoc.xlsx](https://github.com/rabanti-github/NanoXLSX/files/6593997/testdoc.xlsx)

**Comment by rabanti-github** [comment]
Hi,

Thank you for the report.
The problem is that there is formatting on the cells E12, F12 and M12 (Style id 1).
Technically, Excel adds cells to a worksheet (persisted into the file) as soon the cell it is formatted. A value is not even necessary.
So, zero-bases row 11 is technically the last row, although not the last data row.
A possibility is to iterate trough all rows and check every cell in the row for a value. As soon as the last row with data in any cell occurred, the last data row is reached (stop at the number of GetLastRow).

I have considered to implement a function like GetLastDataRow(), but there are probably other functions useful, like RowHasValues() or GetFirstEmptyRow().

These functions may be added with the next minor update. However, to avoid breaking behavior, I would rather not change the behavior of GetLastRow() now. But the documentation of the function may be improved as well.

Thanks again.

**Comment by rgallini** [comment]
Thanks for the explanation. I'll create a row check function and call it from the for/next loop.

**Comment by rgallini** [comment]
Thanks for the explanation. I'll write a function to check the row for data. Does the same logic apply to columns?

**Comment by rabanti-github** [comment]
Yes, it is the same behavior for rows and columns.

Keep in mind that relying on a GetLastRow function as limit (regardless of the library - e.g. POI, nPOI or NanoXLSX) may have a performance impact on the program.
Example: If a worksheet was accidentally completely formatted, the the program has to check 17'178'804'225 cells (16383 columns x 104857 rows) in the worst case.

**Comment by rabanti-github** [comment]
Hello

The new functions:
- GetLastDataRow()
- GetLastDataColumn()
- GetLastCell()
- GetLastDataCell()
... are now incorporated in the recently published version 1.7 of the library

**Comment by rgallini** [comment]
They work great! Thank you for the quick turnaround .
