### ISSUE TITLE
How to fixed the first row?

### ISSUE THREAD

**Issue by robyle** [rabanti-github/NanoXLSX#17]
Exceuse, How to use the nanoxlsx to fixed first row,using the style setting?

**Comment by rabanti-github** [comment]
Hello
I checked it. Row and column fixing, as well as splitting is apparently not implemented yet.
Unfortunately, it cannot be achieved by a style definition, since it is a worksheet property.
However, I think I can implement it fairly easy. I try to do this at the weekend

**Comment by robyle** [comment]
Think you, do you have the slove problem's idea ? I want to trying use NanoXLSX to setting style,but there is no path to think.

**Comment by rabanti-github** [comment]
Hello
I am working on a new version regarding:
- splitting of worksheets into panes
- fixing of split panes in worksheets
- Hiding of worksheets
- Hiding of workbooks
Unfortunately, I was not able to finish the work at the weekend, due to some vaccination-inconveiniences.
I will hopefully release the version this week.

If you have problems with formatting in general, let me know what you want to format, so that I can give you some advice.

**Comment by rabanti-github** [comment]
Work is still in progress for splitting. There are some very strange measurements, exceptions and not really documented rules.
This will take some days more

**Comment by rabanti-github** [comment]
Hello
I just released v1.8 of the library. The NuGet package should be available in some minutes.
You can now split and freeze worksheets in X and Y panes.
you can freeze the first row using:
`wb.CurrentWorksheet.SetHorizontalSplit(1, true, new Address("A2"), Worksheet.WorksheetPane.bottomLeft);`, where
- wb ist the current workbook
- the first parameter '1' ist the row number where the split line is
- the second parameter 'true' indicates that the pane is frozen
- the third parameter 'Address("A2")' is the top left cell of the lower pane
- the fourth parameter 'Worksheet.WorksheetPane.bottomLeft' is the active pane 

Please let me know, if there is any problem with this version.

**Comment by robyle** [comment]
Yeah !  that so nice!  It's works fine. Thank you very much .
