### ISSUE TITLE
Reading cell value - data type DATE

### ISSUE THREAD

**Issue by peropata** [rabanti-github/NanoXLSX#19]
Is it possible to read the cell data as string or unformatted data ? 
I have a excel file, which has column data type correct , (values text and  numbers), but due to saving excel file with openoffice, it get changed to DATE format and then all values are read as dates, which is not usable for our application. 

Can you change the column data type, so the values would be read as string and not date ?

**Comment by rabanti-github** [comment]
Hello
You can try the ImportOptions class: https://github.com/rabanti-github/NanoXLSX/blob/master/NanoXLSX/ImportOptions.cs.
There you can define certain columns with an enforced type when loading an XLSX file.

Create a new instance of the ImportOptions class and then use the methods **AddEnforcedColumn(string columnAddress, ColumnType type)** or **AddEnforcedColumn(int columnNumber, ColumnType type)** to define columns that must be imported as specific types.

The types you can enforce (try if possible) are:
- Numeric (double)
- As Dates (DateTime
- As Times (TimeSpan)
- As Bools
- As String

However, the string option may result in unexpected results. A bool may become "0" or "1" instead of "true" or "false". And Dates may become numbers as string. But if you are interested in numbers, the numeric type may be your option.

You can apply the instance of ImportOptions simply on the **Load** method in the Workbook class (https://github.com/rabanti-github/NanoXLSX/blob/e2272d3772400009040eb7c7df56e79f2aed7627/NanoXLSX/Workbook.cs#L710)

I hope, this helps.

**Comment by peropata** [comment]
Thank you for your answer. I updated the  version and implemented ImportOptions and now it works as you described.
