### ISSUE TITLE
Read wrong value when reading a numeric field.

### ISSUE THREAD

**Issue by thiagossrs** [rabanti-github/NanoXLSX#2]
When reading a numeric cell that contain a decimal value. It reads as an integer number.
This only happens if the regional settings of the computer it's configured to use , (comma) as a decimal deliminator rather then . (dot) as in the us.

A fast workaround is to set the culture of the thread to en-US.

System.Threading.Thread.CurrentThread.CurrentCulture = System.Globalization.CultureInfo.CreateSpecificCulture("en-US");

**Comment by rabanti-github** [comment]
Thanks for the report.

Hm, interesting. Excel uses internally always en-US, as well as the library should too.
It has probably something to do with: [this method](https://github.com/rabanti-github/NanoXLSX/blob/master/NanoXLSX/LowLevel/WorksheetReader.cs#L333). Maybe there is a wrong casting assumption.
Please let me have a look at this tomorrow.

**Comment by rabanti-github** [comment]
Hopefully fixed with commit 55d4974f23aa60aa9d0c744daa822cefe092fa0e.
I could partially reproduce the issue. However, the decimal number was not casted to an int but to a scientific number format. Could be locale specific.
Nevermind, this should be fixed now.

Have you used Nuget, the release or the source files?
Currently only the [source ](https://github.com/rabanti-github/NanoXLSX/blob/master/NanoXLSX/LowLevel/XlsxReader.cs) and the [release](https://github.com/rabanti-github/NanoXLSX/releases/tag/1.3.5) is up to date.
Any chance you could test the fix?
I would publish the Nuget Package afterward ASAP.

Thank you in advance

**Comment by thiagossrs** [comment]
I was using the source files. 

I've just tested. And it's working.
Perfect. This fix the issue.

Thank you very much for the fix.

**Comment by rabanti-github** [comment]
Thank you again for the report and testing.
The NuGet package of version 1.3.5 was published some minutes ago.
Please let me know, if there are any other problems.
