### ISSUE TITLE
Read CellStyleBackground color

### ISSUE THREAD

**Issue by alberti47** [rabanti-github/NanoXLSX#20]
I's there any way to Read the background color assigned to a cell ?

**Comment by rabanti-github** [comment]
Hello
Currently, nothing other than the date and time style (number formats) elements are read.
However, I am working at this time at a full style reader (dev branch). It will probably take some more weeks to finish this full capable style reader.

**Comment by alberti47** [comment]
Thanks for Yr answer and for Yr product.
Currently my project requires not only to read 
data's (excellent work) , but also
to distinguish between white/black color of a cell.
My I ask You , waiting for Yr complete solution, 
some Hints in order to implement
a fast solution to the mentioned problem ? (in 
order to finish a demo program)
Thanks in advance
Best regards


Ing. Gianni Alberti
Email: ***@***.***: 
***@***.******@***.***>
/INFORMAZIONI IMPORTANTI E NOTIFICA DI RISERVATEZZA
Le informazioni contenute nel presente messaggio 
di posta elettronica sono confidenziali e 
riservate al destinatario.
L'accesso alle predette informazioni non è 
autorizzato ai terzi. Qualora Lei non fosse il 
destinatario, né un dipendente,
né un responsabile designato dal destinatario a 
ricevere la Sua posta elettronica, La informiamo 
che ne è vietato qualsiasi uso,
rivelazione, copia e distribuzione a terzi, nonché 
qualsiasi azione diretta od indiretta posta in 
essere a tal fine.
Inoltre qualora Lei non fosse il destinatario 
designato, è pregato di informare il mittente 
ritrasmettendo una copia del presente
messaggio di posta elettronica con la dicitura 
"indirizzo errato" come oggetto e di cancellare il 
messaggio originario,
nonché qualsiasi allegato o copia dello stesso./

Il 17/11/2021 23:11, Raphael Stoeckli ha scritto:

**Comment by rabanti-github** [comment]
What I currently can offer you is following:
Please checkout the dev branch https://github.com/rabanti-github/NanoXLSX/tree/dev
Currently it is 48 commits ahead of the master branch.
The dev branch get currently (between 2 per day and 1 per week) new commits on a regular basis. The current work is to implement the style reader. Borders are already done, number formats partially. I can go next to the Fill section, where the cell background is defined.
However, I have first to rewrite the functions to resolve cell data (WorksheetReader), since it have gotten extremely ugly and inefficient. This is work in progress.
If you check out the dev branch from time to time, the functionality you wish may be already implemented. I cannot tell you exactly when this happens, but I am working on the dev branch on daily basis.

**Comment by rabanti-github** [comment]
Hi
With the just released version 2.0.0, every style property that can we written, can also be read.

Thanks again for filing the issue.
