### ISSUE TITLE
Incomplete worksheet information

### ISSUE THREAD

**Issue by WesolyPierozek** [rabanti-github/NanoXLSX#24]
I'm trying to create Workbook on c# side, to create input for existing matlab script. Currently I'm looking into an issue, that matlab is not able to load worksheet. I'm getting an error "Worksheet not found" from matlab.

After uploading xlsx to office365, and then downloading it from office365 without any change as a copy, matlab is able to load data from second file.
It seems that office365 is adding some missing fields, which matlab requires.

I believe that problem exists in all of 3 libs, matlab, office365 and NanoXLSX, but I have no idea how to deal with that problem.

**Comment by rabanti-github** [comment]
Hello
Can you provide a demo file?
Thank you in advance.

**Comment by WesolyPierozek** [comment]
[After.xlsx](https://github.com/rabanti-github/NanoXLSX/files/8125335/After.xlsx)
[Before.xlsx](https://github.com/rabanti-github/NanoXLSX/files/8125336/Before.xlsx)
Before.xlsx - file created by NanoXLSX.
After.xlsx - file uploaded to office365 and downloaded after opening it.

**Comment by rabanti-github** [comment]
Well, both files are valid when Excel is used. There must be a part that matlab is relying on, which is irrelevant for Excel.
Since I have no matlab license and there seems to be no additional error logs, it is currently only possible to rule out issues by trying to add the allegedly missing parts.
I have tampered with the "before" version and created four variants (see attachments). Could you please try to read these four files with matlab?
As soonas one file can be read, we know the document part that contains the mandatory information for matlab.
The changes are:
* App meta information taken from the 365 version
* Core meta information taken from the 365 version
* Workbook definition is taken from the 365 version
* Definition of worksheet 1 is taken from the 365 version
Other parts seems not to carry substantial changes. And if still no file can be read, "Theme" (which is not implemented in NanoXLSX yet) is the issue.
Can you try to check these files?

Thank you in advance.
 
 **Attachments:**
[extendedWorksheet.xlsx](https://github.com/rabanti-github/NanoXLSX/files/8127945/extendedWorksheet.xlsx)
[extendedApp.xlsx](https://github.com/rabanti-github/NanoXLSX/files/8127946/extendedApp.xlsx)
[extendedCore.xlsx](https://github.com/rabanti-github/NanoXLSX/files/8127947/extendedCore.xlsx)
[extendedWorkbook.xlsx](https://github.com/rabanti-github/NanoXLSX/files/8127948/extendedWorkbook.xlsx)

**Comment by WesolyPierozek** [comment]
Yes I know, and this is not first surprise with xlsx file format.
I didn't tested above files (my matlab model has data which I cannot share), but idea behind that.
Matlab was able to read xlsx only after having **both** extended xl\_rels\workbook.xml.rels and xl\worksheets\*

I've checkec which tags are requried by matlab in xl\worksheets\*.xml.

- worksheet\sheetFormatPr@defaultColWidth attribute is required
- worksheet\dimension@ref="[range]"  is required
- **order** of worksheet/sheetData/row/c@t and worksheet/sheetData/row/c@r matters. **r has to be first.**

**Comment by rabanti-github** [comment]
Hello
Thanks fort he investigation.
I am a little bit conflicted here. Let’s go through the points:
1.	sheetFormatPr: If the attribute defaultColWidth is mandatory, it would not even be possible to create a valid document with Office 2019 or Office 365 for Enterpises. Both suits crate Excel files without this attribute by default… Could be an over-eager demand of MathLab
2.	dimension: That’s reasonable
3.	order of the r and t attribute: Not very happy with that. Seems not to follow the nature of XML attributes (https://www.w3.org/TR/REC-xml/#sec-starttags). I’m not even sure whether this can be reliably implemented with an XML encoder (when not written manually by StringBuilder). Seems again an over-eager MathLab implementation. However, Excel (2019 and 365 fE) have it at the first position
4.	Id attribute in .rels: Again, like point 4
5.	Leading /: That’s reasonable

**Conclusion**:
1 seems not really to be mandatory. 3 and 4 are quite quirky and my be achieved. 2 and 5 are fine.

**Here’s the deal**:
Since the defaultColWidth attribute is not bothering other applicatiosn than MathLab, it can be implemented in NanoXLSX. I can try to fix the attribute orders. This should currently work, since I only use an XML encoder for the last steps during the save process. Building the documents is currently achieved by a Stringbuilder, where I have control over the order. The points 2 and 5 can easily be implemented.

Please give me some days to implement these changes. I have to implement them in parallel with my current dev branch, as well as PicoXLSX and NanoXLSX4j, and have also to define unit tests for the dev branches.

**Comment by rabanti-github** [comment]
Hello,
I have already bad news.
1, 2 and 3 were be implemented.
However, 4 is currently not achievable, since System.IO.Packaging is used. There, I have no control over the order of the attributes (as far as I know). To reorder the attributes, an own resembling version of Packaging has to be created.
5 looked reasonable. However, a relative URI object without leading / is not valid and throws an exception. Same issue as 4.

I have committed the changes from 1-3 into the branch dev-pr. Maybe you can check this out and see whether the changes are sufficient for Mathlab.
If it is not sufficient, maybe you may ask the MathLab support (I know... Difficult topic, since I am too a developer that constantly has to ignore feature requests of my company's users because of the way too long backlog).
To implement a own Packaging routine is at the moment not reasonable, since it looks like a fringe case dute to a bad implementation of the XLSX standard by MathLab. Sorry about that.

If you cannot test the changes of dev-pr, I can make a patch release to test it.
Please let me know whether you could or could not test the changes.

**Comment by WesolyPierozek** [comment]
I expected that news,
On thursday I forked yours main branch and did this "fixes", then I got results which I expected. For System.IO.Packaging I did post process of zip file.
Yes I know that problems are silly, also with order of attributes.
Regarding point 1, I will dig more into it, maybe there is additional magical matlab logic.
I will do merge (but in next days) with yours dev-pr and will come back 👍 .

**Comment by rabanti-github** [comment]
Hello,
I have again bad news.
the attribute defaultColWidth interferes with the pane splitting of worksheets.
And at the moment, I really don't see how to calculate the right default with in combination with pane splitting. The wohle pane split topic is extremely poor documented and I literally needed weeks to figure out how it works. So, at the moment adding this attribute brings more problems than benefits. If I cannot figure out how to use it properly within this week, I have to strip this out, unfortunately.

**Comment by rabanti-github** [comment]
Hello,
I just wanted to report back on this.
As already mentioned, I could not yet satisfy all requirements the reader you mentioned need to work properly.
The problem with defaultColWidth is currently (with the latest release) resolved as following:
If there are no split panes, defaultColumnWidth is used. Otherwise, is is skipped to not interfere with the split column widths (until I have figured out how to counter-calculate).
It's quite a corner case since Office365 online is not even supporting spilt panes so far.

As earlier mentioned, I cannot really manipulate the attribute order and the URI elements of the packing library. So, I have to leave it at the moment as is.

Sorry about that. I will close this issue for now.
But please, re-open or issue a new one if you have news or suggestions how to cope with our importer.
