### ISSUE TITLE
Add hyperlink to cell

### ISSUE THREAD

**Issue by utillity** [rabanti-github/NanoXLSX#43]
**Describe the goal you want to achieve using NanoXLSX**
I want to add a hyperlink (ie. URL) to a cell, so in excel when I click the cell I navigate to the specified URL. This differs from the display-text, which is a human readable text.

In Excel I can click any cell, then press `CTL+K` and insert a URL in the appearing dialog. After that the cell text acts like a hyperlink.

Can someone point me in the right direction?

thanks!

**Comment by rabanti-github** [comment]
Hi,
Hyperlinks are defined as inline formatting (in cells).
This is unfortunately not supported in v2.x.
But it's on top of the [backlog](https://github.com/rabanti-github/NanoXLSX/wiki/Backlog#formulas) of v3.0 and currently under development.
However, I cannot make a prediction when this will be ready because v3.0 will be completely overhauled and there are still many issues to fix and features to implement, until a release.

**Comment by utillity** [comment]
ok, thanks for the info!
