### ISSUE TITLE
vb.net inport into datagridview

### ISSUE THREAD

**Issue by sigster** [rabanti-github/NanoXLSX#46]
How can I inport to datagridview 
I only get long list

Excel file
Name1, Name2, Name3, Name4

Same in Datagridview 
column1,column 2,column 3,column 4 

`    Dim wb As Workbook = Workbook.Load("Importa.xlsx")
        Dim ws As Worksheet = wb.Worksheets(0)
        Dim Cx As Dictionary(Of String, Cell) = ws.Cells`

**Comment by rabanti-github** [comment]
Hello,
I assume, you want to import an Excel file into a System.Windows.Forms.DataGridView (or a System.Windows.Controls.DataGrid?). Since I am not familiar with WinForms anymore, I cannot say it without some research.
However, If you load a Workbook with NanoXLSX, you get the worksheets in the workbook object (workbook.Worksheets). In the worksheets you get a list of Cells. Each cell has a CellAddress, either represented by:
- A 0-based column number and a 0-based row number
- An address object (contains column, row and reference information)
- A string representation of the address (e.g. "C10")
With this information you can either fill your data grid or create a two-dimensional array ([COL][ROW]) of values.

**ChatGPT** suggests following (**NOTE! This is not tested, nor presented as solution**. The AI was fed with the NanoXLSX classes and then asked about an implementation. **This is just meant as "inspiration"**):

You can fill a DataGridView with the content of all cells from a Worksheet object with the following steps:

Get the Worksheet object you want to display in the DataGridView by accessing the Worksheets property of the Workbook object and using the index 0 to get the first Worksheet object.

Create a new DataTable object to hold the data from the Worksheet.

Add columns to the DataTable object for each column in the Worksheet. You can use the Cells property of the Worksheet object to get the number of columns and their names.

Add rows to the DataTable object for each row in the Worksheet. You can use the Cells property of the Worksheet object to get the number of rows.

Set the DataSource property of the DataGridView object to the DataTable object.

Here is some sample code that demonstrates how to do this:
```c#
// Get the first worksheet from the workbook
Worksheet worksheet = workbook.Worksheets[0];

// Create a new DataTable to hold the data from the worksheet
DataTable dataTable = new DataTable();

// Add columns to the DataTable for each column in the worksheet
foreach (var cell in worksheet.Cells)
{
    string columnName = CellHelper.GetColumnName(cell.Key);
    if (!dataTable.Columns.Contains(columnName))
    {
        dataTable.Columns.Add(columnName, typeof(object));
    }
}

// Add rows to the DataTable for each row in the worksheet
for (int rowIndex = 0; rowIndex <= worksheet.Cells.Max(cell => cell.Value.CellAddress2.Row); rowIndex++)
{
    DataRow dataRow = dataTable.NewRow();

    foreach (var cell in worksheet.Cells)
    {
        if (cell.Value.CellAddress2.Row == rowIndex)
        {
            string columnName = CellHelper.GetColumnName(cell.Key);
            dataRow[columnName] = cell.Value.Value;
        }
    }

    dataTable.Rows.Add(dataRow);
}

// Set the DataSource property of the DataGridView to the DataTable
dataGridView.DataSource = dataTable;
```

**Comment by sigster** [comment]
Thanks 

this works :)

Regards
Sigster

**Comment by rabanti-github** [comment]
Thanks for the feedback.
I will close the issue now.
Please reopen or create a new one, if other problems occur.
