### ISSUE TITLE
Edit existing file when Save lost all styles

### ISSUE THREAD

**Issue by SepuWeb** [rabanti-github/NanoXLSX#5]
Hi,
I use the command **WorkBook.Load** to load an existing file, I edit it only by adding some cells, in the end I use command **SaveAs**, but the file lost all styles.

Thank you.

**Comment by rabanti-github** [comment]
Hello,
Unfortunately, this is a limitation of the library.
The reader does not support styles at the moment. It simply neglects all non-essential parts like styles, themes or printer setup. So, this information is not preserved.
A style reader is planned, but still under construction. But even if implemented, style transfer is a possible minefield, since Styling is badly documented and has many strange interconnections.

Maybe you have to look for another solution. Have you considered NPOI or even interior, if Office is installed on the target machine?

**Comment by SepuWeb** [comment]
Ok, thank you, I'll try NPOI.
