### ISSUE TITLE
Numbers are rounded when they shouldn't be

### ISSUE THREAD

**Issue by datamadsen** [rabanti-github/NanoXLSX#52]
**Bug description**
We have seen a number of times that amounts in Excel are getting rounded of in weird ways. Please see the attached xlsx file for an example where 4372449.78 is rounded to 4372450 after reading it with NanoXLSX.

**Steps To Reproduce**
Steps to reproduce is shown here: https://github.com/rabanti-github/NanoXLSX/pull/51/commits/da00f28877074a516e38ebc58d899ea7f69186e6#diff-ab6f3e2c36de0c57128180f0a5bb2e99cbc6b003609f5122cf243bea2a8c6598

**Expected behavior**
I would expect the number not to be rounded off, but instead be parsed to the same number as I can see in Excel (4372449.78 in this case)

[large-ish-amount.xlsx](https://github.com/rabanti-github/NanoXLSX/files/11109330/large-ish-amount.xlsx)

**Comment by rabanti-github** [comment]
Hi,
Thank you for the report and the PR.
Sorry for the late feedback.
I will checkout your changes and examine the mentioned tests.
I have to say, that it was extremely time consuming to set up these tests and to fine-tune the reader to parse the seemingly appropriate types. There is a quite high complexity when it comes to reading numbers. However, I first have to look at the changes. I will give you a feedback as soon as possible

**Comment by rabanti-github** [comment]
Hi,
I looked at the PR. There are two issues with the current implementation of it.
1.	The implementation breaks the principle “what-you-can-write-is-what-you-can-read”. This means that many tests will fail that are writing a float/decimal-like number and try to read the same value as validation. However, this may be wanted or may not be wanted in practice
2.	The implementation will break compatibility for the existing library users when they update the NanoXLSX. This may be especially dangerous (in a minor update) since it may introduce a bug depending on not yet known data from XLSX file that are be read

However, your point is certainly valid. But I would suggest an adaption to keep compatibility and to keep the existing tests (almost) untouched.

Let’s define a new ImportOption flag **`AllSingleToDecimal`**, similar to the existing ones like `AllNumbersToDouble` or `AllNumbersToDecimal`.
Then, we can switch between the old and the new behavior.
1.	Define a new enum value in **ImportOptions.cs** --> `GlobalType.AllSingleToDecimal`
2.	Add a if statement in WorksheetReader.cs, line 1299
a.	Enclose `return dcValue` if `importOptions.GlobalEnforcingType.AllSingleToDecimal` is set
b.	Use the old code in the else case
4.	Adapt the feature test with an import option when loading the workbook.

This should work quite easily. If you want, I can do PR comments at the mentioned code positions.
Thank you in advance.

**Comment by rabanti-github** [comment]
The PR was merged into the branch dev-pr.
I will do some minor adaptions and administrative stuff before merging into den and master, and before the release.
Thank you very much for the contribution

**Comment by datamadsen** [comment]
Thank you too :)

**Comment by rabanti-github** [comment]
I will close this issue for now
