### ISSUE TITLE
NanoXLSX  or PicoXLSX  what is the difference ? which one to choose?

### ISSUE THREAD

**Issue by blackholeearth** [rabanti-github/NanoXLSX#62]
hi,  i see you have 2 libraries. **NanoXLSX  and PicoXLSX** .

1) what is the difference ? 

2) which one should i use ??

3) if they are same, why not archive the worse repo ??  
reduce your trouble??

i am confused as a user ? which one i should choose?

thanks.

**Comment by rabanti-github** [comment]
Hi,
1. PicoXLSX is a Writer-Only, NanoXLSX can read and write Excel worksheets. Both libraries share the same logical core
2. NanoXLSX, if you want to read and write, or PicoXLSX if you just want to write with the least possible dependencies and overhead. If you don't mind: **NanoXLSX**
3. PicoXLSX is a subset of NanoXLSX. In a future version, PicoXLSX will become a meta-package with just writer abilities (for compatibility), and NanoXLSX will become a meta-package with all features. Archiving PicoXLSX is at the moment not planned, since both libraries are with each >100K downloads similarly popular on [Nuget.org](https://www.nuget.org/profiles/rabanti)

**Comment by blackholeearth** [comment]
thanks.  i will use NanoXlsx .  i need both ability. read and write.
